config/routes.rb
Rails.application.routes.draw do
  resources :posts
  post 'contact_us' => 'notifications#contact_us'
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def contact_us
    ContactMailer.contact_us(params[:name], params[:email], params[:message]).deliver_now

    redirect_to root_path, notice: 'Thank you!'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	layout false
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mri</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notifications/_form.slim
header
  h2
    | Let’s work together
  p
    | Send us a message
  = form_tag contact_us_path do
    .row
      .6u
        = text_field_tag :name, nil, placeholder: 'Name'
      .6u
        = email_field_tag :email, nil, placeholder: 'Email'
    .row
      .12u
        = text_area_tag :message, nil, placeholder: 'Message'
    .row
      .12u
        ul.actions
          li
            = submit_tag "Send Message"

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table
  thead
    tr
      th Title
      th
      th
      th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = link_to 'Show', post
        td = link_to 'Edit', edit_post_path(post)
        td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path

app/views/welcome/index.html.slim
doctype html
html
  head
    title
      | Webtisans
    meta[http-equiv="content-type" content="text/html; charset=utf-8"]
    meta[name="description" content=""]
    meta[name="keywords" content=""]
    script[src="js/jquery.min.js"]
    script[src="js/jquery.scrolly.min.js"]
    script[src="js/jquery.poptrox.min.js"]
    script[src="js/skel.min.js"]
    script[src="js/init.js"]
    noscript
      link[rel="stylesheet" href="css/skel.css"]
      link[rel="stylesheet" href="css/style.css"]
    = stylesheet_link_tag 'application'
  body
    - if flash[:notice].present?
      #notice
        = flash[:notice]
    section#header
      header
        h1
          | WEBTISANS
        p
          | Under development
      footer
        a.button.style2.scrolly-middle[href="#contact"]
          | Contact us
    article.container.box.style3#contact
      = render 'notifications/form'
    section#footer
      .copyright
        ul.menu
          li
            | © Webtisans. All rights reserved.
          li
            | Design: 
            a[href="http://html5up.net"]
              | HTML5 UP